// Generated by scripts/generate-brand-assets.ts — do not edit.
export const PHOTOS = {
  "building-1": {
    src: "/brand/photos/building-1.jpg",
    blur: "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgMF/8QAIBAAAgICAgIDAAAAAAAAAAAAAQIEEQADEiEFIjFBYf/EABUBAQEAAAAAAAAAAAAAAAAAAAAC/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAECIRESE//aAAwDAQACEQMRAD8A0Wn6Oaqr25+a+svokrs5F3DKPzvAUbyEnRM9H6JqiMaBjrjKVq2FnHVqyNIusH//2Q==",
    width: 2000,
    height: 1500,
  },
  "building-2": {
    src: "/brand/photos/building-2.jpg",
    blur: "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQEE/8QAIBAAAgIBAwUAAAAAAAAAAAAAAQIAAwQFETESEyFBYf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAIREzH/2gAMAwEAAhEDEQA/AFa9NWy3e4HtjmTNwqjlgUqAu3ESZj0uvoGZU82qfsdmtIxScP/Z",
    width: 2000,
    height: 1336,
  },
  "building-3": {
    src: "/brand/photos/building-3.jpg",
    blur: "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABgf/xAAdEAACAQUBAQAAAAAAAAAAAAABAgQAAwURITES/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABcRAQADAAAAAAAAAAAAAAAAAAEAEjH/2gAMAwEAAhEDEQA/ACsO4zTlurwg7GqoeOZZccNz7HoqfwFCygg8pLirz2szYCNxhoimsmQqjs//2Q==",
    width: 2000,
    height: 2667,
  },
  "building-4": {
    src: "/brand/photos/building-4.jpg",
    blur: "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQP/xAAfEAACAgIBBQAAAAAAAAAAAAABAgMRAAQFEhNBUWH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABcRAAMBAAAAAAAAAAAAAAAAAAABAhH/2gAMAwEAAhEDEQA/AF5dyEhEhVQPJOS5/SSfjw8bhCg6ifmC6cfc23Vneq94jxxZ4HEjs4JK0xsVk1eIFJ//2Q==",
    width: 2000,
    height: 2000,
  },
  "hero-dusk": {
    src: "/brand/photos/hero-dusk.jpg",
    blur: "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIFBv/EACAQAAIBBAIDAQAAAAAAAAAAAAECAwAEBSEREgYxQUL/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABsRAAEFAQEAAAAAAAAAAAAAAAEAAgMREjFR/9oADAMBAAIRAxEAPwDPX+QbIX5dtJvoo+U0lwBDFGW/WxVPDRRyqjPGnbn3xR5FawxqjogBI3xU3T4Oa6k2ESC/F//Z",
    width: 2000,
    height: 3000,
  },
  "hero-evening": {
    src: "/brand/photos/hero-evening.jpg",
    blur: "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwQFBv/EACAQAAICAgAHAAAAAAAAAAAAAAECAwQAEhETFCEyQVH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABkRAAEFAAAAAAAAAAAAAAAAAAACERIiMf/aAAwDAQACEQMRAD8AlkdZKpDcxj3I4Y/KlKlXV2ibcjxOZSvZmXVlcgj2MPPZmlUF3LEfcJqciuH/2Q==",
    width: 2000,
    height: 1333,
  },
  "hero-villa": {
    src: "/brand/photos/hero-villa.jpg",
    blur: "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAAF/8QAHxAAAgEDBQEAAAAAAAAAAAAAAQIDAAQxBRESEyGR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgP/xAAXEQEBAQEAAAAAAAAAAAAAAAABEQAC/9oADAMBAAIRAxEAPwCuZHeQ9czoAu5FK0wR3ds6zEsRgke1lzgt6WONs0jS55Lfl1t9pxG3SOjoib//2Q==",
    width: 2000,
    height: 1333,
  },
} as const;

export type PhotoName = keyof typeof PHOTOS;

export const SPLASH_SCREENS = [
  {
    href: "/splash/splash-1320x2868-light.png",
    media:
      "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1320x2868-dark.png",
    media:
      "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1206x2622-light.png",
    media:
      "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1206x2622-dark.png",
    media:
      "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1290x2796-light.png",
    media:
      "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1290x2796-dark.png",
    media:
      "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1179x2556-light.png",
    media:
      "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1179x2556-dark.png",
    media:
      "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1284x2778-light.png",
    media:
      "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1284x2778-dark.png",
    media:
      "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1170x2532-light.png",
    media:
      "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1170x2532-dark.png",
    media:
      "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1080x2340-light.png",
    media:
      "(device-width: 360px) and (device-height: 780px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1080x2340-dark.png",
    media:
      "(device-width: 360px) and (device-height: 780px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1242x2688-light.png",
    media:
      "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1242x2688-dark.png",
    media:
      "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-828x1792-light.png",
    media:
      "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-828x1792-dark.png",
    media:
      "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1125x2436-light.png",
    media:
      "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1125x2436-dark.png",
    media:
      "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1242x2208-light.png",
    media:
      "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1242x2208-dark.png",
    media:
      "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-750x1334-light.png",
    media:
      "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-750x1334-dark.png",
    media:
      "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-640x1136-light.png",
    media:
      "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-640x1136-dark.png",
    media:
      "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-2048x2732-light.png",
    media:
      "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-2048x2732-dark.png",
    media:
      "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1668x2388-light.png",
    media:
      "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1668x2388-dark.png",
    media:
      "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1640x2360-light.png",
    media:
      "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1640x2360-dark.png",
    media:
      "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1668x2224-light.png",
    media:
      "(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1668x2224-dark.png",
    media:
      "(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1620x2160-light.png",
    media:
      "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1620x2160-dark.png",
    media:
      "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1536x2048-light.png",
    media:
      "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1536x2048-dark.png",
    media:
      "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
  {
    href: "/splash/splash-1488x2266-light.png",
    media:
      "(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)",
  },
  {
    href: "/splash/splash-1488x2266-dark.png",
    media:
      "(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)",
  },
] as const;
