/**
 * Demo seeder (§15). Generates `supabase/seed.sql` from the deterministic demo
 * dataset (src/demo/demo-data.ts) and, with `--apply`, executes it against
 * DATABASE_URL. `supabase db reset` also loads the generated seed.sql.
 *
 *   pnpm seed            → regenerate seed.sql and apply it (truncates demo tables!)
 *   pnpm seed --no-apply → only regenerate seed.sql
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { config } from "dotenv";
import postgres from "postgres";
import { buildDemoData, DEMO_PASSWORD, type DemoData } from "../src/demo/demo-data";
import { INVESTMENT_TEMPLATE, RESIDENTIAL_TEMPLATE } from "../src/domain/template-seeds";
import { buildTemplateVars, renderContract, type ContractTemplate } from "../src/domain/templates";

config({ path: path.resolve(import.meta.dirname, "../.env.local") });

type Val = string | number | boolean | null | undefined | readonly string[] | Record<string, unknown> | unknown[];

function lit(v: Val): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "string") return `'${v.replace(/'/g, "''")}'`;
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) {
    return `array[${(v as string[]).map(lit).join(",")}]::text[]`;
  }
  return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
}

function insert(table: string, rows: Record<string, Val>[]): string {
  if (rows.length === 0) return "";
  const cols = Object.keys(rows[0]!);
  const chunks: string[] = [];
  for (let i = 0; i < rows.length; i += 500) {
    const values = rows
      .slice(i, i + 500)
      .map((r) => `(${cols.map((c) => lit(r[c])).join(", ")})`)
      .join(",\n  ");
    chunks.push(`insert into public.${table} (${cols.join(", ")}) values\n  ${values};`);
  }
  return chunks.join("\n");
}

export const SYSTEM_TEMPLATE_IDS = {
  residential: "2d000000-0000-4000-8000-000000000001",
  investment: "2d000000-0000-4000-8000-000000000002",
} as const;

function templateRows(tpl: ContractTemplate, id: string) {
  return {
    template: {
      id,
      org_id: null,
      type: tpl.type,
      name: tpl.name,
      version: 1,
      family_id: id,
      preamble: tpl.preamble,
      closing: tpl.closing ?? null,
      is_default: true,
    },
    clauses: tpl.clauses.map((c) => ({
      org_id: null,
      template_id: id,
      position: c.position,
      key: c.key,
      body: c.body,
      condition: c.condition ?? null,
      default_condition: c.defaultCondition ?? null,
      optional: c.optional ?? false,
      default_enabled: c.defaultEnabled ?? true,
    })),
  };
}

export const DEFAULT_ORG_SETTINGS = {
  proration: false,
  dueDay: 1,
  allocationStrategy: "fifo",
  receiptDuplicatePolicy: "warn",
  digits: "latn",
  letterhead: true,
  poweredBy: true,
  accent: "ink",
  voucherThresholdFils: 500000,
  lateReminderDays: [3, 7, 15, 30],
  numbering: { contractResidential: "R", contractInvestment: "I", receipt: "RC", voucher: "EX" },
  reminderTemplateAr:
    "السلام عليكم {{tenant_name}}،\nنود تذكيركم بوجود مبلغ مستحق قدره {{amount}} د.ك عن {{months}} للوحدة {{unit}} في {{property}}.\nنرجو التكرم بالسداد في أقرب وقت. شكرًا لكم.\n{{org_name}}",
  reminderTemplateEn:
    "Hello {{tenant_name}},\nThis is a friendly reminder that {{amount}} KWD is due for {{months}} for unit {{unit}} at {{property}}.\nThank you.\n{{org_name}}",
};

export function buildSeedSql(d: DemoData): string {
  const out: string[] = [];
  const org = d.org.id;
  out.push("-- Generated by scripts/seed.ts — do not edit by hand.");
  out.push("-- Fictional demo data (§15). Password for all demo users: " + DEMO_PASSWORD);
  out.push("begin;");
  out.push("set local timezone = 'Asia/Kuwait';");
  const auditTables = [
    "contracts",
    "charges",
    "payments",
    "payment_allocations",
    "adjustments",
    "expense_vouchers",
    "expense_lines",
    "expense_allocations",
    "deposits",
    "legal_cases",
    "owners",
    "properties",
    "units",
    "tenants",
    "org_members",
    "monthly_closings",
  ];
  for (const t of auditTables) out.push(`alter table public.${t} disable trigger audit_${t};`);

  // Clean slate (demo only).
  out.push(
    "truncate public.orgs, public.contract_templates, public.template_clauses, public.audit_log, public.user_settings restart identity cascade;",
  );
  out.push(`delete from auth.identities where user_id in (${d.users.map((u) => lit(u.id)).join(", ")});`);
  out.push(`delete from auth.users where id in (${d.users.map((u) => lit(u.id)).join(", ")}) or email like '%@demo.test';`);

  // Auth users.
  for (const u of d.users) {
    out.push(`insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', ${lit(u.id)}, 'authenticated', 'authenticated', ${lit(u.email)}, crypt(${lit(DEMO_PASSWORD)}, gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', ${lit({ display_name: u.displayName })}, now(), now(), '', '', '', '');`);
    out.push(`insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), ${lit(u.id)}, ${lit(u.id)}, ${lit({ sub: u.id, email: u.email, email_verified: true })}, 'email', now(), now(), now());`);
  }

  // System templates.
  const res = templateRows(RESIDENTIAL_TEMPLATE, SYSTEM_TEMPLATE_IDS.residential);
  const inv = templateRows(INVESTMENT_TEMPLATE, SYSTEM_TEMPLATE_IDS.investment);
  out.push(insert("contract_templates", [res.template, inv.template]));
  out.push(insert("template_clauses", [...res.clauses, ...inv.clauses]));

  out.push(insert("orgs", [{ id: org, name: d.org.name, name_en: d.org.nameEn, settings: DEFAULT_ORG_SETTINGS }]));
  out.push(
    insert(
      "org_members",
      d.users.map((u) => ({ org_id: org, user_id: u.id, role: u.role, display_name: u.displayName, email: u.email, phone: null })),
    ),
  );
  out.push(
    insert(
      "user_settings",
      d.users.map((u) => ({ user_id: u.id, org_id: org, locale: "ar", onboarding_done: true, sessions_count: 3 })),
    ),
  );
  out.push(
    insert(
      "owners",
      d.owners.map((o) => ({
        id: o.id,
        org_id: org,
        full_name: o.fullName,
        civil_id: o.civilId,
        phones: o.phones,
        email: o.email,
        iban: o.iban,
        bank_name: o.bankName,
        portal_user_id: o.portalUserId,
      })),
    ),
  );
  out.push(
    insert(
      "properties",
      d.properties.map((p) => ({
        id: p.id,
        org_id: org,
        name: p.name,
        name_en: p.nameEn,
        area: p.area,
        block: p.block,
        street: p.street,
        avenue: p.avenue,
        house_or_plot: p.houseOrPlot,
        paci_no: p.paciNo,
        property_type: p.propertyType,
        floors: p.floors,
        cover_image_path: p.coverImage,
      })),
    ),
  );
  out.push(
    insert(
      "property_owners",
      d.properties.map((p) => ({ org_id: org, property_id: p.id, owner_id: p.ownerId, share_pct: 100 })),
    ),
  );
  out.push(
    insert(
      "units",
      d.units.map((u) => ({
        id: u.id,
        org_id: org,
        property_id: u.propertyId,
        label: u.label,
        sort_order: u.sortOrder,
        type: u.type,
        floor: u.floor,
        area_m2: u.areaM2,
        bedrooms: u.bedrooms,
        bathrooms: u.bathrooms,
        paci_no: u.paciNo,
        asking_rent_fils: u.askingRentFils,
        available_since: "2025-01-01",
      })),
    ),
  );
  out.push(
    insert(
      "tenants",
      d.tenants.map((t) => ({
        id: t.id,
        org_id: org,
        full_name: t.fullName,
        civil_id: t.civilId,
        nationality: t.nationality,
        phones: t.phones,
      })),
    ),
  );

  const tenantById = new Map(d.tenants.map((t) => [t.id, t]));
  const ownerById = new Map(d.owners.map((o) => [o.id, o]));
  const propById = new Map(d.properties.map((p) => [p.id, p]));
  const unitById = new Map(d.units.map((u) => [u.id, u]));
  out.push(
    insert(
      "contracts",
      d.contracts.map((c) => {
        const prop = propById.get(c.propertyId)!;
        const owner = ownerById.get(prop.ownerId)!;
        const tenant = tenantById.get(c.tenantId)!;
        const tpl = c.type === "residential" ? RESIDENTIAL_TEMPLATE : INVESTMENT_TEMPLATE;
        const vars = buildTemplateVars({
          contractNo: c.contractNo,
          type: c.type,
          contractDate: c.contractDate,
          startDate: c.startDate,
          firstCollectionDate: c.firstCollectionDate,
          endDate: c.endDate,
          termMonths: c.termMonths,
          autoRenew: c.autoRenew,
          monthlyRentFils: c.monthlyRentFils,
          purpose: c.purpose,
          utilitiesParty: c.utilitiesParty,
          electricityFixedFils: c.electricityFixedFils,
          freeMonths: c.freeMonths,
          noticePeriodMonths: c.noticePeriodMonths,
          securityDepositFils: c.securityDepositFils,
          owner: { name: owner.fullName, civilId: owner.civilId, phones: owner.phones },
          tenant: { name: tenant.fullName, civilId: tenant.civilId, phones: tenant.phones },
          property: { ...prop, propertyType: prop.propertyType },
          units: c.unitIds.map((id) => {
            const u = unitById.get(id)!;
            return { label: u.label, type: u.type, paciNo: u.paciNo };
          }),
        });
        return {
          id: c.id,
          org_id: org,
          contract_no: c.contractNo,
          type: c.type,
          template_id: SYSTEM_TEMPLATE_IDS[c.type],
          tenant_id: c.tenantId,
          property_id: c.propertyId,
          owner_id: prop.ownerId,
          contract_date: c.contractDate,
          start_date: c.startDate,
          first_collection_date: c.firstCollectionDate,
          term_months: c.termMonths,
          end_date: c.endDate,
          auto_renew: c.autoRenew,
          monthly_rent_fils: c.monthlyRentFils,
          purpose: c.purpose,
          utilities_party: c.utilitiesParty,
          electricity_fixed_fils: c.electricityFixedFils,
          free_months: c.freeMonths,
          notice_period_months: c.noticePeriodMonths,
          security_deposit_fils: c.securityDepositFils,
          deposit_status: c.securityDepositFils > 0 ? "held" : "none",
          status: c.status,
          clause_overrides: c.clauseOverrides,
          rendered_clauses: renderContract(tpl, vars, c.clauseOverrides) as unknown as Record<string, unknown>,
          activated_at: null,
        };
      }),
    ),
  );
  out.push(
    insert(
      "contract_units",
      d.contracts.flatMap((c) => c.unitIds.map((unitId) => ({ org_id: org, contract_id: c.id, unit_id: unitId }))),
    ),
  );
  out.push(
    insert(
      "charges",
      d.charges.map((ch) => ({
        id: ch.id,
        org_id: org,
        contract_id: ch.contractId,
        period: ch.period,
        kind: ch.kind,
        amount_fils: ch.amountFils,
        waived_value_fils: ch.waivedValueFils,
        due_date: ch.dueDate,
      })),
    ),
  );
  out.push(
    insert(
      "payments",
      d.payments.map((p) => ({
        id: p.id,
        org_id: org,
        tenant_id: p.tenantId,
        contract_id: p.contractId,
        amount_fils: p.amountFils,
        method: p.method,
        received_at: p.receivedAt,
        receipt_no: p.receiptNo ?? null,
        system_no: p.systemNo,
        collected_by: p.collectedBy,
      })),
    ),
  );
  out.push(
    insert(
      "payment_allocations",
      d.allocations.map((a) => ({ org_id: org, payment_id: a.paymentId, charge_id: a.chargeId, amount_fils: a.amountFils })),
    ),
  );
  out.push(
    insert(
      "expense_categories",
      d.categories.map((c) => ({ id: c.id, org_id: org, name_ar: c.nameAr, name_en: c.nameEn, type: c.type })),
    ),
  );
  out.push(
    insert(
      "beneficiaries",
      d.beneficiaries.map((b) => ({ id: b.id, org_id: org, name: b.name, kind: b.kind, monthly_salary_fils: b.monthlySalaryFils })),
    ),
  );
  out.push(
    insert(
      "expense_vouchers",
      d.vouchers.map((v) => ({
        id: v.id,
        org_id: org,
        voucher_no: v.voucherNo,
        voucher_date: v.date,
        paid_from: v.paidFrom,
        recipient_name: v.recipientName,
        notes: v.notes,
        status: "posted",
      })),
    ),
  );
  out.push(
    insert(
      "expense_lines",
      d.vouchers.flatMap((v) =>
        v.lines.map((l) => ({
          id: l.id,
          org_id: org,
          voucher_id: v.id,
          position: l.position,
          amount_fils: l.amountFils,
          category_id: l.categoryId,
          beneficiary_id: l.beneficiaryId,
          description: l.description,
          allocation_mode: l.mode,
        })),
      ),
    ),
  );
  out.push(
    insert(
      "expense_allocations",
      d.vouchers.flatMap((v) =>
        v.lines.flatMap((l) =>
          l.allocations.map((a) => ({ org_id: org, expense_line_id: l.id, property_id: a.propertyId, unit_id: a.unitId, amount_fils: a.amountFils })),
        ),
      ),
    ),
  );
  const haris = d.beneficiaries.find((b) => b.kind === "staff")!;
  out.push(
    insert("recurring_expenses", [
      {
        org_id: org,
        category_id: d.categories[0]!.id,
        beneficiary_id: haris.id,
        amount_fils: haris.monthlySalaryFils ?? 0,
        description: "راتب الحارس الشهري",
        allocation: { mode: "single", targets: [{ propertyId: d.properties[0]!.id }] },
        day_of_month: 26,
        last_generated_period: "2026-08",
      },
    ]),
  );
  out.push(
    insert(
      "deposits",
      d.deposits.map((x) => ({
        id: x.id,
        org_id: org,
        deposit_date: x.date,
        amount_fils: x.amountFils,
        destination: x.destination,
        owner_id: x.ownerId,
        bank_name: x.bankName,
        reference: x.reference,
      })),
    ),
  );
  out.push(
    insert(
      "deposit_properties",
      d.deposits.flatMap((x) => x.properties.map((p) => ({ org_id: org, deposit_id: x.id, property_id: p.propertyId, amount_fils: p.amountFils }))),
    ),
  );
  out.push(
    insert(
      "legal_cases",
      d.legalCases.map((l) => ({
        id: l.id,
        org_id: org,
        contract_id: l.contractId,
        tenant_id: l.tenantId,
        case_no: l.caseNo,
        court: l.court,
        type: l.type,
        status: l.status,
        amount_claimed_fils: l.amountClaimedFils,
        next_hearing_date: l.nextHearingDate,
        lawyer: l.lawyer,
      })),
    ),
  );
  out.push(
    insert(
      "legal_case_events",
      d.legalCases.flatMap((l) => [
        { org_id: org, case_id: l.id, event_date: "2026-08-10", title: "رفع الدعوى", notes: "تم قيد الدعوى لدى إدارة الكتاب" },
        { org_id: org, case_id: l.id, event_date: "2026-09-08", title: "الجلسة الأولى", notes: "تأجيل لتقديم المستندات" },
      ]),
    ),
  );

  // Number sequences reflect what the demo already used.
  const seqRows = new Map<string, { key: string; year: number; last: number }>();
  const bump = (key: string, year: number, n: number) => {
    const k = `${key}-${year}`;
    const cur = seqRows.get(k);
    if (!cur || cur.last < n) seqRows.set(k, { key, year, last: n });
  };
  for (const c of d.contracts) {
    const [prefix, year, n] = c.contractNo.split("-");
    bump(prefix === "R" ? "contract_residential" : "contract_investment", Number(year), Number(n));
  }
  for (const p of d.payments) {
    const [, year, n] = p.systemNo.split("-");
    bump("receipt", Number(year), Number(n));
  }
  bump("voucher", 2026, d.vouchers.length);
  out.push(insert("number_sequences", [...seqRows.values()].map((s) => ({ org_id: org, key: s.key, year: s.year, last_value: s.last }))));

  // July 2026 is closed (month-closing demo).
  out.push(insert("monthly_closings", [{ org_id: org, period: "2026-07", closed_by: d.users[0]!.id, notes: "إقفال شهر يوليو 2026" }]));

  for (const t of auditTables) out.push(`alter table public.${t} enable trigger audit_${t};`);
  out.push("commit;");
  return out.filter(Boolean).join("\n\n") + "\n";
}

async function main() {
  const sql = buildSeedSql(buildDemoData());
  const file = path.resolve(import.meta.dirname, "../supabase/seed.sql");
  writeFileSync(file, sql);
  console.log(`wrote ${file} (${(sql.length / 1024).toFixed(0)} KB)`);
  if (process.argv.includes("--no-apply")) return;
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.log("DATABASE_URL not set — skipping apply. Run `supabase db reset` to load seed.sql.");
    return;
  }
  const db = postgres(url, { max: 1, onnotice: () => {} });
  try {
    await db.unsafe(sql);
    console.log("seed applied");
  } finally {
    await db.end();
  }
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
